### ISSUE TITLE
Dataset properties

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#10]
Collect properties of ideal dataset (and then ask on twitter)

- should be speech related
- ideally super intuitive even for non-phoneticians (to make it compatible with other linguists)
- ideally open data set of published study that
   - has run a frequentist analysis
   - did not use the full random effect structure
- contains at least one continuous variable
- contains at least two additional variables (categorical because easier to interpret, ideally 2x2). 
- contains at least one grouping variable

to be honest, Bodo's original pitch dataset kind of ticks many of these boxes, but very few data points, but I could ask him for the whole data set from this paper [here](https://www.sciencedirect.com/science/article/pii/S0095447012000666).

**Comment by jvcasillas** [comment]
That would be a great idea (using Bodo's dataset). Especially because many people already have experience with his tutorial, so it would be natural to extend it to BDA.
