### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#14]
Bodos dataset

(doesn't support upload of .csvs here LOL)

[POP.txt](https://github.com/learnB4SS/learnB4SS/files/5894539/POP.txt)

**Comment by stefanocoretta** [comment]
Working on it. BTW, there is a binary variable: `musicstudent` (yes or no)!

**Comment by jvcasillas** [comment]
I was just going to include this, but it looks like you've got it. I am going to get the github.io site repo started.

**Comment by stefanocoretta** [comment]
✅ On master branch.

To do:
- [ ] Document dataset.
- [ ] Data cleaning if necessary, variables renaming, etc.
