### ISSUE TITLE
Package website

### ISSUE THREAD

**Issue by stefanocoretta** [learnB4SS/learnB4SS#15]
The package website is not compiling because it depends on a package that has been just recently updated and there aren't binary versions available yet, so the GH action fails. It should work in the next few days though. Just a heads up.

**Comment by jvcasillas** [comment]
Which package is it? I had a few issues with `withr` recently and I wondering if that might be the culprit.

**Comment by stefanocoretta** [comment]
rappdir. It's on the global mirror so I could switch to that.
