### ISSUE TITLE
Reasons for switching to Bayes

### ISSUE THREAD

**Issue by stefanocoretta** [learnB4SS/learnB4SS#17]
A random list of reasons.

## Practical reasons

- Fitting frequentist models can lead to anti-consevative *p*-values (meaning increased false positive rate: there is no effect and yet you got a significant *p*-value). Another interesting example of this for the non-technically inclined reader can be found here: https://365datascience.com/bayesian-vs-frequentist-approach/. LMER tends to be more sensitive to small sample sizes than Bayesian models (with small sample sizes, Bayesian models return estimates with greater uncertainty, which is a more conservative approach).
- While very simple models will return very similar confidence and credible intervals, in most cases more complex models won't fit if run with frequentist packages like lme4, especially with not adequate enough sample sizes. So, BRMs always converge, while LMERs don't always do.
- In reality, LMERs require as much work as BRMs, although the common practice is to skip most of the necessary steps when fitting LMERs which gives the impression of LMERs being quicker. Factoring out the time needed to run MCMCs in BRMs, in LMER you still have to perform robust perspective power analysis and post-hoc model checks.
- With BRMs, you can iteratively reuse posterior distributions from previous work, which effectively speeds up the discovery process (getting to the real value faster). In other words, you can embed previous knowledge in BRMs while you can't in LMERs.

## Conceptual reasons

- LMER cannot provide evidence for a difference between groups, only evidence to reject the null hypothesis.
- While a frequentist CI only tell us n% of the time if we run the study multiple times that that CI contains the real value (but we don't know whether the CI we got is one of those 5% CIs that DO NOT CONTAIN the real value), a Bayesian CrI ALWAYS tell us that the real value is within a certain range at n% probability. (Of course all conditional on the model and data, which is true both for frequentist and Bayesian models alike). So, LMER really just gives you a point estimate, while BRMs give a range of values.
- With BRM you can compare any H, not just Null vs Alternative. (Although you can use Info Criteria with LMER).
- LMER is based on an imaginary set of experiments that you never actually carry out.
- BRM will converge towards the true value in the long run. LMER does not.

Of course, there are merits in fitting LMERs, for example in corporate decisions, but you'll still have to do a lot of work. The main conceptual difference then is that LMER and BRMs answer very different questions and as (basic) scientists we are generally interested in questions that BRMs can answer and LMER cannot.

**Comment by jvcasillas** [comment]
Very clear and succinct. 👍🏼

**Comment by stefanocoretta** [comment]
Oh I just noticed that I had already posted this in Discussions :D oh well.
