### ISSUE TITLE
Blurb for website

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#18]
Draft: 

"Our understanding of human speech is increasingly shaped by quantitative data. It is thus of critical importance to evaluate quantitative findings inferentially. This workshop aims at introducing Bayesian inference for the quantification of phonetic data. Following other scientific disciplines, the last decades where dominated by statistical inference within the null-hypothesis-significance-testing framework. This framework comes with many conceptual challenges and pitfalls, and comes with technical limitations that prevent us from analyzing our data in an appropriate way. More recently, many researchers have started to use an alternative inferential framework: Bayesian inference. Bayesian inference more closely answers the research questions we ask; it is much more flexible; and it allows us to run appropriate statistical tests. Until recently, this framework was technically very involved and represented computational challenges. These challenges have now been overcome, making Bayesian inference conceptually, technically, and computationally feasible for researchers across disciplines.
This workshop will introduce the logic of Bayesian inference and contrast it to null-hypothesis-significance-testing. After a brief conceptual introduction, the course will walk through a Bayesian statistical analysis using R and the package brms (Bürkner 2017), explaining how to set up a Bayesian regression model (including setting appropriate priors), how to test ‘hypotheses’ (including parameter estimation and Bayes factor), how to interpret the results, how to diagnose model convergence, and how to visualize and report the results. In hands-on exercises, the participants will immediately apply their knowledge to new data sets in R."

**Comment by jvcasillas** [comment]
Copied this to an issue in the website repo: https://github.com/learnB4SS/learnB4SS.github.io/issues/2
