### ISSUE TITLE
How to share screen recordings

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#25]
Hey, I have screen recorded my short intro to Bayes theorem and will do the initial WHY session. How should we share these videos. What would be a good workflow?

**Comment by stefanocoretta** [comment]
Perhaps just wetransfer? Dropbox? iCloud Drive (I have the 200 GB plan)?

**Comment by troettge** [comment]
@jvcasillas @stefanocoretta shared first two videos with you using wetransfer
