### ISSUE TITLE
Prepare and document data table

### ISSUE THREAD

**Issue by stefanocoretta** [learnB4SS/learnB4SS#29]
Bodo's data table for practicals.

**Comment by stefanocoretta** [comment]
@troettger Could you check with Bodo about the meaning of the variable in the dataset?

**Comment by troettge** [comment]
From the paper, most of the columns are clear. I'll ask him about the remaining ones. We can also toss some of these columns if we happen to not need them at the end.

index	                 unique row identifier (DELETE)
subject                     unique identifier of participant (categorical)
gender			sex of participant (categorical: M,F)
birthplace		birth place of participants (categorical)
musicstudent		???whether the participant has received musical training or not (binary: yes, no)
years_in_ger		years lived in Germany at time of recording (DELETE)
months_in_ger	months lived in Germany at time of recording  
scenario			???
task				???
attitude			politeness context (binary: pol(ite), inf(ormal))
total_duration	        ???total duration of utterance in seconds (numeric)
articulation_rate	syllables per second (numeric)
f0mn			mean of fundamental frequency (numeric)
f0sd				standard deviation of fundamental frequency (numeric)
f0range			max-  min of fundamental frequency (numeric)
inmn			mean of intensity (numeric)
insd				standard deviation of intensity (numeric)
inrange			max-  min of intensity (numeric)
shimmer			local shimmer (likewise normalized amplitude difference of consecutive periods) (numeric)
jitter				local jitter (absolute period-to-period difference divided by the average period) (numeric)
HNRmn			mean Harmonics-to-Noise ratio (numeric)
H1H2			difference between first and second harmonics (numeric)
breath_count		number of audible breath intakes (count)
filler_count		number of oral fillers like “oh/ah“ (count)
hiss_count		number of noisy breath intakes (count)
nasal_count		number of nasal fillers like “mh/nh” (count)
sil_count			number of silent pauses (count)
ya_count		        number of interjection “ya” (informal) (count)
yey_count 		number of interjection “yey” (polite) (count)

**Comment by troettge** [comment]
updated code book

**Comment by stefanocoretta** [comment]
Done. The data table is now called `polite`.
