### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#31]
Dump your favorite online resources (apps / shinyapps) and books / paper here for the last session

**Comment by stefanocoretta** [comment]
- [Shiny app](https://nanx.shinyapps.io/conjugate-normal-umkv/) showing Bayesian update.
- [Advanced Bayesian Multilevel modelling](https://journal.r-project.org/archive/2018/RJ-2018-017/index.html).
- [How to become a Bayesian in eight easy steps: An annotated reading list](https://link.springer.com/article/10.3758/s13423-017-1317-5)

**Comment by stefanocoretta** [comment]
* [Ordinal Regression Models in Psychology: A Tutorial](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiLwtb23oXxAhXLhqQKHYOBCjkQFjACegQIAhAD&url=https%3A%2F%2Fosf.io%2Fgyfj7%2Fdownload&usg=AOvVaw2AFvfgcnio_V8QpKGPoVTQ) has a nice box on page 12 on "Basics of Bayesian Statistics".
