### ISSUE TITLE
Showreel

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#32]
What should we show in the show reel at the end? Some fancy stuff you can do in principle with BRMS.
- Maybe a GAM-like model with splines?
- Mixture model?
-

**Comment by jvcasillas** [comment]
I actually wasn't too sure what this even was, but I think I understand now. I always enjoy seeing cool ways of plotting uncertainty. Perhaps some cool plots. Is this what you meant by GAM-like model with splines and a mixture model?

**Comment by troettge** [comment]
No I though of demonstrating that you can do tons of things with brms, which everybody is used to do with different tools / R packages. So a show reel of brms really.

**Comment by jvcasillas** [comment]
Ah I follow now. 

- Drift diffusion models
- regression with index variables (a la McElreath) using nl syntax
- GPs

**Comment by stefanocoretta** [comment]
* Phylogenetic models.
* Clustering.
