### ISSUE TITLE
Check installation instructions for C++ tools, Rstan, brms

### ISSUE THREAD

**Issue by stefanocoretta** [learnB4SS/learnB4SS#34]
Hey guys, can you have a look at the installation instructions?

https://learnb4ss.github.io/learnB4SS/articles/install-brms.html

**Comment by troettge** [comment]
This is great!!! Some minor comments/suggestions:

# MacOS
- "First, if you have the files ~/.R/Makevars and/or ~/.Renviron" --> where do people find these, what are these? This is Chinese to most people.
- "If the model compiles and starts sampling" --> worth mentioning what that would look like? (same below)
- "Restart R" is underlined which is a little odd, triggers my "this is a link" senses
- "The end." Maybe something more friendly like "Congrats, you are ready to run Bayesian models"? (same below)

# Windows:
- "To configure the C++ toolchain, follow the instructions here for you R version" --> for your R Version

**Comment by jvcasillas** [comment]
- Agreed on the first point. I don't think most attendees will know about hidden files in general, and much less about Makevars and .Renviron. I guess this should be the first step (creating these files). Something like...

> First, if you have the files ~/.R/Makevars and/or ~/.Renviron, save a copy in a different location (like your desktop) and delete them. If you are not sure what these files are or if you have them, do this...

- It is also probably safe to assume users won't know what the terminal is either

> run the following in the terminal:

We could link to a site to manually download. In fact, isn't this through the app store now? That might make things much easier. 

- When we tell users to restart R we could add something like (Session > Restart R in the RStudio menu)
- Regarding Timo's comment ("If the model compiles and starts sampling"), we could add a screenshot.

**Comment by stefanocoretta** [comment]
Thanks, interesting points!

For Terminal, I'll add how to open it and run the command more explicitly. From the App Store you can only download all of Xcode which is 7+ GB, while with command you only install the CLTs which is about 200 MBs.

For the R files, I will link to how to show hidden files and more detailed instructions (they have only to delete them if they exists, not create them).

Restart R: I'll take the underline away, and I will add the menu breadcrumbs.

Compilation: I'll take a screenshot and add it

**Comment by stefanocoretta** [comment]
Updated as per comments (5495963). Website is building and will be ready in a few minutes!

**Comment by jvcasillas** [comment]
Looks great! Nice work. I dig the gifs.

**Comment by stefanocoretta** [comment]
Cool! If you guys think it's ready to go, @troettge you can ask Molly to send info to the people who already signed up  and we can also post on Twitter?

**Comment by troettge** [comment]
Looks great! Thanks so much for putting this together. Also love the GIFs, add important tangible information. Will there be a link from our landing page? or should we just distribute the link you posted here? @stefanocoretta

**Comment by stefanocoretta** [comment]
That's a good idea! I'll add a link to our landing page too!
