### ISSUE TITLE
CHECK: Email to participants

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#35]
Dear Bayesian enthusiasts,

we are very much looking forward to meeting you all and giving you an introduction on Bayesian data analysis in R using the wonderful and truly game-changing package brms. Our landing page contains the most important information about the workshop.

For you to get the most out of the workshop, we would like to seize the moment and manage expectations. Bayesian Inference is a powerful tool that requires somewhat complex computational resources. We need to prepare ourselves for that.

Moreover, we won’t have time to troubleshoot individual problems with running brms on individual machines during the workshop, we can do our best to assist you before the workshop. Brms has several dependencies and compiles Stan code in C++ under the hood. You don’t need to understand either of these things, but the computations that run in the background are more complex than our everyday R shenanigans. Thus, we highly recommend that we all try our best to fix these issues in advance with the help of capable IT staff and our colleagues. Here, we give you a head start and since we still have three weeks, we are confident that we can get most machines in shape.

To prepare your laptops for brms and its dependencies…

(1)   please download / update to the latest version of R: https://cran.r-project.org/mirrors.html

(2)   I also highly recommend, installing RStudio, as we will provide you with RMarkdown files as additional resources to review after the workshop. Please download / update the latest version of RStudio: https://www.rstudio.com/products/rstudio/download/#download

(3) Now we need our Bayesian engine. We have written a detailed step-by-step guide, to get your machine ready for this here:
https://learnb4ss.github.io/learnB4SS/articles/install-brms.html

Now this should make 95% of you operational! Some of you might have idiosyncratic issues that are difficult to predict. Again, we hope that you can try to approach capable colleagues at your university to help you solve these things.

In order to streamline our communication in general, we have set up a Slack Channel for all of you. Here we can share resources, ask questions and give answers or simply hang out and being social. It is obviously not mandatory to join the channel, but we think it provides an additional layer of helpful communication and a sense of community. We are all rookies in the domain of statistical inference, but we are keen to learn from and with each other.

If you don’t have Slack, you can download it here: https://slack.com/intl/en-no/

To join our Slack channel, click this link: 
####

We are really looking forward to meeting all of you in July.

Cheers,
Timo, Joseph & Stefano

**Comment by troettge** [comment]
the reference to R and Rstudio could also go on the instruction page for redundancy

**Comment by stefanocoretta** [comment]
Editing [here](https://docs.google.com/document/d/1uGDVnGQUpQbrXZZ3r_4aqP4deMkysm3ArZkOYyaJ3ps/edit)
