### ISSUE TITLE
Session 03 slides: Add presenter notes

### ISSUE THREAD

**Issue by stefanocoretta** [learnB4SS/learnB4SS#37]

**Comment by stefanocoretta** [comment]
I am working on adding notes but I think it would be best if we can have a quick meeting, perhaps on Wed so i can talk you through them.

**Comment by troettge** [comment]
I'll start my norsk classes this week, I won't be able to meet beyond our Friday slot. Would be great if you found an asynchronous solution or you guys go ahead and meet without me.

**Comment by stefanocoretta** [comment]
Write, no probs Timo! @jvcasillas, do you have 10/15 minutes tomorrow or Wed?

**Comment by jvcasillas** [comment]
Tomorrow should be fine @stefanocoretta
