### ISSUE TITLE
NOTES ON DATA

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#38]
- The articulation rate variable is slightly skewed, which might be a great example later on for using pp_check and using alternative distributional assumptions.

**Comment by jvcasillas** [comment]
I like the suggestion. Sounds good. The fit with default priors isn't all that bad. I assume with more regularization it's probably a moot point, but a good teaching moment nonetheless. 

<img width="988" alt="Screen Shot 2021-06-16 at 21 04 49" src="https://user-images.githubusercontent.com/1747068/122314743-c4885100-cee6-11eb-8c59-d301cd2e6584.png">

**Comment by stefanocoretta** [comment]
This is fun and a nice example of subjectivity: for me, that fit ain't that great! I love science.

**Comment by jvcasillas** [comment]
hehe I agree it ain't great either. I guess a more accurate description is that it's not a bad start.
