### ISSUE TITLE
nhst v bayes ready for comments

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#44]
video [here](https://osf.io/a7vwq/). Please comment here.

**Comment by jvcasillas** [comment]
Again this is quite good. I'd consider changing "theory" in p(data|theory) and p(theory|data) to "hypothesis". Also, at one point you say "p(dead|decapitated) is near 0". I think you mean it's 1.

**Comment by troettge** [comment]
I'm kind of terrified by an American using "quite good". Isn't that equivalent to what other languages refer to as utter trash? :D

**Comment by stefanocoretta** [comment]
No further comments your honour.

**Comment by jvcasillas** [comment]
> I'm kind of terrified by an American using "quite good". Isn't that equivalent to what other languages refer to as utter trash? :D
> 
> Thanks for the comments tho haha

haha somehow I missed the "quite good" comment. To me it doesn't mean utter trash 😂
I'd have something more colorful to say if that were the case 🤐 haha
