### ISSUE TITLE
Exercise Rmd

### ISSUE THREAD

**Issue by stefanocoretta** [learnB4SS/learnB4SS#49]
## Sessions with exercises

- [x] ~02. Bayes theorem~
- [x] 03. Priors
- [x] 07. Bayesian inference
- [x] 08. Leveling up

## How to

**EDIT**

@troettge @jvcasillas 

The package now provides two functions:

- `open_slides()` to open a session's slides in the browser (e.g. `open_slides(1)`).
- `open_exercise()` to open a copy of the exercise Rmd in the editor (e.g. `open_exercise(3)`).

To create an exercise Rmd, run (adapt session number and title):

```r
usethis::use_vignette("ex_03", title = "Application to regression II - The prior and Bayesian updating")
```

**EDIT** the argument below should be `eval` not `echo`.

~Make sure to set `echo = FALSE` in `knitr::opts_chunk$set()`.~

Make sure to set `eval = FALSE` in `knitr::opts_chunk$set()`.

The data table can be loaded with:

```r
library(learnB4SS)
data("polite")
```

----------

I will write a function that opens the exercise Rmd file of a session in the editor (after copying it into the working directory).

We can just create vignettes in the package learnB4SS by naming them according to the session title. Best if we use the same names as in the folders in the slides repository.

The participants will just have to run:

```r
open_exercise(session = 1)
```

They will also be able to see the knitted versions from the package website.

So you can go ahead and create vignettes in the package as the exercise Rmd files.

**Comment by jvcasillas** [comment]
Awesome idea and very boomer friendly

**Comment by troettge** [comment]
boomer friendly is my jam

**Comment by stefanocoretta** [comment]
You can create the exercise vignettes with code like:

```
usethis::use_vignette("ex_03_a2r_prior_and_bayesian_updating", "Application to regression II - The prior and Bayesian updating")
```

The file name (first argument) must begin with a letter (not a number), so I added `ex_` before the session number (the name I took from the folder names in the slide repo), and the title (second argument) is the name of the session in the links from the slide repo.

**Comment by stefanocoretta** [comment]
I have updated the package data. Now called `b4ss_data`. I'm working on writing the functions now.

**Comment by stefanocoretta** [comment]
Change of heart about the file name: `ex_00` is enough and will be easier to write the functions

**Comment by troettge** [comment]
where and how should we store exercise solutions?

**Comment by jvcasillas** [comment]
> where and how should we store exercise solutions?

If you open the b4ss package Rproj you can use the code Stef mentioned and it will create the file for you, then you save it in the vignettes folder. @stefanocoretta , correct me if I'm wrong.

**Comment by stefanocoretta** [comment]
We could just add them as Rmd comments (with HTML comment tags) in the vignette. I can take care of that.

**Comment by stefanocoretta** [comment]
We could just add them as Rmd comments (with HTML comment tags) in the vignette. I can take care of that.

**Comment by jvcasillas** [comment]
This is really cool. Just tested the open_slides and open_exercise functions and they worked perfectly. I'm very impressed. I did get this warning when building the vignettes (just as you mentioned, Stef): 

```
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       ‘learnB4SS/vignettes/b_mod_00.rds’ ‘learnB4SS/vignettes/b_mod_01.rds’
─  building ‘learnB4SS_0.1.0.tar.gz’
```

So once you move those around I think everything will be perfect. 

Also, when running r command check there is now a note, which seems to be caused by me using ggplot2 and dplyr.
