### ISSUE TITLE
Check package new landing page

### ISSUE THREAD

**Issue by stefanocoretta** [learnB4SS/learnB4SS#50]
https://learnb4ss.github.io/learnB4SS/

**Comment by jvcasillas** [comment]
I like it. Should we add a link to the slack channel as well? Maybe another subsection like "Where can I get more help?" or something like that.

**Comment by stefanocoretta** [comment]
We can mention it, but I would keep the link private.

**Comment by troettge** [comment]
Keep the link private, but maybe link the link  to the page in the Slack channel?

**Comment by stefanocoretta** [comment]
Yes, I will when the package is ready.

**Comment by stefanocoretta** [comment]
I added a mention to the slack workspace in the landing page and added a link to the faqs in the q&a slack channel.
