### ISSUE TITLE
Questionnaire feedback

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#51]
survey [here](https://docs.google.com/forms/d/1-mSsmH64g7ray97dwqNMytzNoguG9SElGYeTa1VABbg/edit).

Cool! Two things:

- Career stage. Its multiply choice but overlapping categories and missing ones. Postgrad and Doctoral student overlap, Postdoc and ECR overlap, Category between assistant prof/lecturer and full professor is missing (associate /reader). I'd say: students vs. phd student vs. postdoc vs. faculty (early career = Assistant & Associate Professor) vs. faculty (late career = Full Professor)
- Minorities, make sure you don't forget a major category in the example listing

@stefanocoretta

**Comment by stefanocoretta** [comment]
Eh, I see what you mean, the issue is the difference between BE and AE labels. "Faculty" is AE only (BE doesn't use the term that way). ERC also includes postdocs I guess. Any other ideas?

**Comment by stefanocoretta** [comment]
Perhaps "Early career (staff/faculty)" / "Late career (staff/faculty)"?
