### ISSUE TITLE
Priors

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#53]
What priors to use and how to explain?

- normal(0,10) for population-levels for articulation rate 
- normal(0,10) for group-levels for articulation rate 
- LKJ(2) for correlation

If we keep it simple in the applications and maybe extend it in the take-home exercises (to say student-t and cauchy) would probably suffice. For now, normal might be good enough? Dunno. What do you think?

**Comment by stefanocoretta** [comment]
I will show them normal and Cauchy for intercept, pop-level eff, and standard deviation. Cauchy extends to group-level effs.

**Comment by troettge** [comment]
@stefanocoretta your session also uses articulation rate right? What Cauchy specification do you concretely plan to using?

**Comment by stefanocoretta** [comment]
Yes, I will be using articulation rate. I don't have the priors yet, I will complete the exercise Rmd later today. You can check what I have done so far on the `ex-03` branch of `learnB4SS`.

**Comment by stefanocoretta** [comment]
I completed the draft for the exercise of session 03. You can check it out on the `ex-03` branch.

I think it would be nice to add some visual aid, something like this: https://uomresearchit.github.io/r-day-workshop/03-loading-data-into-R/

**Comment by troettge** [comment]
- l78: "slope term" --> maybe worth using a more familiar term like predictor coefficient ?
- l107ff: maybe put reminder in brackets what these terms mean? it's not trivial. Because dummy coded, the intercept is the reference level for example). 

Nice! Is this for the live coding or as resource for later?

**Comment by stefanocoretta** [comment]
Resource for later! Live Coding I assumed we would do it from the console? I was thinking of just running R in the terminal.
