### ISSUE TITLE
Q&A function on Zoom

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#56]
as far as I understand, the Q&A function is only available for webinars which a special kind of zoom meeting I don't have access to (and is restricted with my account to 100 participants). @stefanocoretta do you know more about this and do you know what LMU has access to?

**Comment by stefanocoretta** [comment]
I was about to write about the same. No, LMU doesn't allow turning on webinar functions...

**Comment by jvcasillas** [comment]
I have two zoom accounts (Middlebury and Rutgers) and neither give me this option either. Some of my colleagues at Midd have more privileges than I do. I will ask them if I can get access or maybe use their account. I wouldn't count on this though.

**Comment by stefanocoretta** [comment]
We can use https://support.google.com/docs/answer/6386827?co=GENIE.Platform%3DDesktop&hl=en
