### ISSUE TITLE
exercise07 up

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#57]
still need to add inference at the end and we need to change naming conventions when we agreed on it. Please have a look and give feedback (typos you can just edit and push)

**Comment by stefanocoretta** [comment]
Looks good, I made a few formatting changes. We might want to move session 08 before session 07 since you mention regularising and weakly informative priors, which are dealt with only in session 08 (see comment in the timeline gdoc).

**Comment by troettge** [comment]
thanks, agree, we can swap them!
