### ISSUE TITLE
Day3

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#58]
Still a big question mark: What do you want to do?

Just 1:1 sessions with people? If we do 15 minutes and we take three breaks (à 15 minutes), we could meet 13 people each. That is 39 people in total which is maybe a realistic number of people that would want to make use of this offer.

What do you think?

**Comment by jvcasillas** [comment]
That seems like a good idea. I'm all for that being plan A. We would need to do a google doc or something as a sign up sheet for time slots. We could talk about that at the end of Tuesday and then give them until Friday to sign up. That way we can gauge interest and possibly resort to a plan B, if we want. I'm not sure what would make us want a plan B... maybe if too many people (more than 39) sign up? Or we could just cap it and a plan B might not be necessary at all. 

If we go this route we could also have them give a bit of info about their questions, i.e., conceptual, technical, or r related.
