### ISSUE TITLE
Live coding of Level Up - Up

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#59]
Please have a look and comment!

https://osf.io/wa85j/

**Comment by stefanocoretta** [comment]
Looks good! I will have already introduced them to HalfCauchy for sigma/sd so perhaps we can go with that? Should we all live code in RStudio then?

**Comment by jvcasillas** [comment]
> Looks good! I will have already introduced them to HalfCauchy for sigma/sd so perhaps we can go with that? Should we all live code in RStudio then?

I think it is a good idea for us to live code in the same environment. RStudio is probably the common denominator between the three of us.
