### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by stefanocoretta** [learnB4SS/learnB4SS#63]
Tick the checkmarks if complete **and** in the `slides` repo.

- [x] [Introduction](https://learnb4ss.github.io/slides/00_intro/index.html)
- [x] [Application to regression I - Demo](https://learnb4ss.github.io/slides/01_a2r_initial_demo/index.html)
- [x] [Bayes theorem - How does it work?](https://learnb4ss.github.io/slides/02_bayes_theorem/index.html)
- [x] [Application to regression II - The prior and Bayesian updating](https://learnb4ss.github.io/slides/03_a2r_prior_and_bayesian_updating/index.html)
- [x] [NHST vs. Bayesian inference](https://learnb4ss.github.io/slides/04_nhst_vs_bayesian_inference/index.html)
- [x] [Interim review](https://learnb4ss.github.io/slides/05_review/index.html)
- [x] [Application to regression III - More Bayesian inference](https://learnb4ss.github.io/slides/06_a2r_inference_over_posterior/index.html)
- [x] [Application to regression IV - Leveling up](https://learnb4ss.github.io/slides/07_a2r_leveling_up/index.html)
- [x] [More on priors](https://learnb4ss.github.io/slides/08_more_priors_likelihoods/index.html)
- [x] [Sampling from the posterior](https://learnb4ss.github.io/slides/09_sample_the_posterior/index.html)
- [x] [Wrap up](https://learnb4ss.github.io/slides/10_wrap_up/index.html)

**Comment by stefanocoretta** [comment]
Tick the checkmarks if complete **and** in the `slides` repo.

**Comment by jvcasillas** [comment]
Like complete complete? I'd say like 99% done, but I wanted to update presenter notes and add references to the last slide.

**Comment by stefanocoretta** [comment]
Not complete complete, just > 95% done :D
