### ISSUE TITLE
Session naming conventions

### ISSUE THREAD

**Issue by stefanocoretta** [learnB4SS/learnB4SS#65]

**Comment by troettge** [comment]
?

**Comment by stefanocoretta** [comment]
Numbering and names of the sessions:

00 Introduction
01 Application to regression I - Demo
02 Bayes theorem - How does it work?
03 Application to regression II - Priors and Bayesian updating
04 NHST vs. Bayesian inference

05 Interim review
06 Application to regression III - More Bayesian inference
08 > 07 More on priors
07 > 08 Application to regression IV - Leveling up
09 Sampling from the posterior
10 Wrap up
