### ISSUE TITLE
Posterior_predictive check

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#68]
Does anyone introduce posterior predictive checks? if so where exactly?

In what session are convergence issues, Rhat etc. handled?

**Comment by jvcasillas** [comment]
I don't have that in any of my sessions. I just took a look at the schedule and I don't think it is covered. Where do you all think would be a good fit?

**Comment by troettge** [comment]
I thought you would cover it in the last session (that was my understanding at least). Possible to incorporate it? 

I think we need to show them how to critically evaluate their fit using posterior predictive checks
- one good example is if you don't use gender as a covariate for pitch, the fit will be off
We also need to anticipate issues that can arise when fitting: 
- rhat
- effective sampling
- mixture of chains (generally iterations, warm-up and chains are never explained anywhere, I thought thats covered in the last content session)

Ideally they do a little hands-on in which they get a convergence warning (via picking the right seed) and need to fix it by either adding more samples

So thats a lot of content that is completely missing. I think its an important part and we should have it somewhere.. what do you guys think

**Comment by stefanocoretta** [comment]
I treat prior predictive checks in session 08 (> now 07) so not a good idea to show posterior predictive checks before then.

We were having an idea of mentioning issues of sampling in session 09 and then treat them on the third day (we can prepare models with divergences and so on they can try out).
