### ISSUE TITLE
Names, branding, logos, etc.

### ISSUE THREAD

**Issue by jvcasillas** [learnB4SS/learnB4SS#7]
Creating this issue for documenting ideas I come up with over the course of the week. Feel free to ignore, comment, and/or include your ideas. Will delete later.

- Key terms
    - bayesian data analysis
    - bayesian approaches
    - bayesian framework
    - speech sciences
    - linguistics
    - linguists
- Ideas for org. names
    - bda4ss (bayesian data analysis for speech sciences, this kind of looks like it says 'badass')
    - b4ss (bayes for speech sciences)
    - bda4ling (bayesian data analysis for linguists)

meh

**Comment by troettge** [comment]
I think the SS abbreviation is kind of difficult ^^ and should be avoided (literally at all costs).  Having said that, I do like bda4ss and its badass reading. Too casual? Maybe? Do we care? Well I certainly not :D

**Comment by stefanocoretta** [comment]
What about "bass" Bayesian Analysis for the Speech Sciences? It also happens to be homophonous with Bayes.

**Comment by jvcasillas** [comment]
So far they all seem ok-ish but none strike me as "the one"

**Comment by jvcasillas** [comment]
If this wasn't decided yet... We can also consider "language practitioner" to form acronyms. 

- BALP
- BA4LP
