### ISSUE TITLE
Logo edited

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#70]
logo in .png and .svg [here](https://osf.io/uxg4h/).

**Comment by stefanocoretta** [comment]
Vielen dank!

**Comment by jvcasillas** [comment]
Logo updated on main landing page via https://github.com/learnB4SS/learnB4SS.github.io/commit/3d62261db5cada5013884839ef6d476ca3e04411

and in b4ss-theme (for all xaringan slides) via https://github.com/learnB4SS/b4ss-theme/commit/7150153f63562933161fb9871bbdd56ff470c004
