### ISSUE TITLE
odd thing in ex_07 exercise (section 2)

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#71]
So in the exercise I want them to do f0_mn + attitude, specify prior, run model, do inference and then pp_check to realize that f0 is bimodal and the model does not account for that.

However, when I run 

f0mn ~ 
    attitude +
    (1 | subject) +
    (0 + attitude | subject)

the simulated draws have already a bimodal pattern. Adding gender as a fixed effect does not change the visual fit. Is this because you basically account for this interspeaker pattern by the random intercepts? But they should be assuming a normal distribution of the random intercept variance, right? Don't understand. Anyone an idea?

**Comment by stefanocoretta** [comment]
Yes, the intercept is already accounting for that. The prob distr of the data doesn't have to look Gaussian, only the residuals, and here they mostly do because within each subject the data in approximately Gaussian.

**Comment by troettge** [comment]
I thought so, but it still puzzles me, something to talk about in the future maybe
