### ISSUE TITLE
Showreel

### ISSUE THREAD

**Issue by troettge** [learnB4SS/learnB4SS#73]
Working on final slides now, for the showreel, I'd love to add some of your papers / open data. Do you have papers for the following categories (should be brms and open data):

(edited, only looking for this now)
- GAM or growth curve

Please post ref and repo link if you have

**Comment by stefanocoretta** [comment]
- Bernoulli (logistic) regression: <https://github.com/stefanocoretta/bayes-regression/blob/master/bayes-reg-3.pdf>
- Multivariate regression: <https://cran.r-project.org/web/packages/brms/vignettes/brms_multivariate.html>
- GAM: <https://fromthebottomoftheheap.net/2018/04/21/fitting-gams-with-brms/>

**Comment by troettge** [comment]
> * Bernoulli (logistic) regression: https://github.com/stefanocoretta/bayes-regression/blob/master/bayes-reg-3.pdf
> * Multivariate regression: https://cran.r-project.org/web/packages/brms/vignettes/brms_multivariate.html
> * GAM: https://fromthebottomoftheheap.net/2018/04/21/fitting-gams-with-brms/

thanks, but I am not looking for tutorials, rather published studies in our field that people can use as a departure point!. But these are great to maybe distill at a separate place.

**Comment by troettge** [comment]
update found one for multivariate modelling
