### ISSUE TITLE
open_exercise function throws error

### ISSUE THREAD

**Issue by jvcasillas** [learnB4SS/learnB4SS#76]
@stefanocoretta I just had a colleague install the starter kit and she gets an error with `open_exercise(03)` (with and without quotations marks around the number). 

```
open_exercise(“ex_08”)
x Session ex_08 does not have exercises! Choose Session 03, 06, or 08.


open_exercise(03)
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
vignette ‘ex_03’ not found

open_exercise(“03”)
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
vignette ‘ex_03’ not found
```

**Comment by stefanocoretta** [comment]
Yup, my bad. In any case, we are not ready yet for people to install the package.

**Comment by stefanocoretta** [comment]
I fixed the installation instr (I forgot to add `build_vignettes = TRUE`). Timo has to do some final touches to his exercise, then I'll send out an email to the attendants.

**Comment by jvcasillas** [comment]
Ok. I'll take advantage then and remove the pvalue garbage ;)
